### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by aetna-softwares** [TheTechy/jslists#2]
Hi,

I found your lib interesting. Is it possible that you do a github release to have a clear stable version number ?

**Comment by TheTechy** [comment]
Hi

Yes this will happen in in 2018 (hopefully by end of Q1 time permitting).
This is/was very early code so wont reflect the quality/features for V1

Thanks
George

**Comment by aetna-softwares** [comment]
great news !

2017-12-28 10:31 GMT+01:00 TheTechy <notifications@github.com>:

**Comment by TheTechy** [comment]
Hi @aetna-softwares 

Better late than never, an update!

I have created a new project called **[ultree](https://github.com/TheTechy/ultree)** (https://github.com/TheTechy/ultree). This will be the future home for this project.

ultree is at version 1 release and there a few new functions. A search, a filter, close & open functions.

Please have a look and let me have any feedback.

Thanks
George
